root: true
env:
  es2022: true
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2022
  sourceType: module
plugins:
  - "@typescript-eslint"
extends:
  - "plugin:@typescript-eslint/recommended"
